# Generated by Django 6.0.2 on 2026-07-09 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Exclusive to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
