# Generated by Django 6.0.2 on 2026-07-29 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='uuid',
            field=models.UUIDField(default=None, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='uuid',
            field=models.UUIDField(default=None, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: [
                apps.get_model('offers', 'CategoryOffer').objects.filter(pk=obj.pk).update(uuid=uuid.uuid4())
                for obj in apps.get_model('offers', 'CategoryOffer').objects.filter(uuid__isnull=True)
            ],
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: [
                apps.get_model('offers', 'ProductOffer').objects.filter(pk=obj.pk).update(uuid=uuid.uuid4())
                for obj in apps.get_model('offers', 'ProductOffer').objects.filter(uuid__isnull=True)
            ],
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
