# Generated by Django 6.0.2 on 2026-07-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_payment_status_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
