# Generated by Django 6.0.2 on 2026-04-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categroy',
            new_name='category',
        ),
    ]
