# Generated by Django 6.0.2 on 2026-07-22 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
